export const recipes = [
  {
    slug: "lemon-garlic-pasta",
    name: "Lemon Garlic Pasta",
    description: "A bright, comforting pasta tossed with lemon, garlic, and parmesan.",
    ingredients: [
      "12 oz pasta",
      "3 tbsp olive oil",
      "3 cloves garlic, thinly sliced",
      "1 lemon, zested and juiced",
      "1/2 cup grated parmesan",
      "Salt and black pepper",
    ],
    category: "Vegetarian",
    time: "25 min",
    accent: "bg-amber-100 text-amber-900",
    instructions: [
      "Cook the pasta in well-salted water according to the package directions. Reserve 1 cup of pasta water, then drain.",
      "Warm the olive oil in a large pan over medium-low heat. Add the garlic and cook until fragrant, about 1 minute.",
      "Add the lemon zest, lemon juice, drained pasta, and a splash of pasta water. Toss until glossy, adding more pasta water as needed.",
      "Stir in the parmesan, season with salt and black pepper, and serve warm.",
    ],
  },
  {
    slug: "weeknight-chicken-tacos",
    name: "Weeknight Chicken Tacos",
    description: "Smoky spiced chicken with crunchy slaw and a squeeze of lime.",
    ingredients: [
      "1 lb boneless chicken thighs",
      "1 tsp paprika",
      "1/2 tsp ground cumin",
      "8 small tortillas",
      "2 cups shredded cabbage",
      "1 lime",
      "1 tbsp olive oil",
      "Salt and black pepper",
    ],
    category: "Quick & easy",
    time: "30 min",
    accent: "bg-rose-100 text-rose-900",
    instructions: [
      "Season the chicken with paprika, cumin, salt, and black pepper.",
      "Heat the olive oil in a skillet over medium heat. Cook the chicken for 5–7 minutes per side, until cooked through. Rest briefly, then slice.",
      "Warm the tortillas in a dry pan. Toss the cabbage with a squeeze of lime juice.",
      "Fill each tortilla with chicken and cabbage. Serve with the remaining lime cut into wedges.",
    ],
  },
  {
    slug: "creamy-tomato-soup",
    name: "Creamy Tomato Soup",
    description: "A cozy tomato soup finished with cream and fresh basil.",
    ingredients: [
      "1 tbsp olive oil",
      "1 small onion, diced",
      "2 cloves garlic, minced",
      "1 can (28 oz) crushed tomatoes",
      "2 cups vegetable broth",
      "1/2 cup heavy cream",
      "1/4 cup fresh basil leaves",
      "Salt and black pepper",
    ],
    category: "Comfort food",
    time: "35 min",
    accent: "bg-orange-100 text-orange-900",
    instructions: [
      "Warm the olive oil in a pot over medium heat. Add the onion and cook until softened, about 5 minutes.",
      "Stir in the garlic and cook for 30 seconds. Add the tomatoes and vegetable broth, then bring to a gentle simmer.",
      "Simmer for 20 minutes. Carefully blend until smooth, then return the soup to the pot.",
      "Stir in the cream and most of the basil. Season to taste and garnish with the remaining basil.",
    ],
  },
  {
    slug: "crispy-chickpea-bowls",
    name: "Crispy Chickpea Bowls",
    description: "Golden chickpeas, fluffy rice, and a cool herby yogurt sauce.",
    ingredients: [
      "1 can (15 oz) chickpeas, drained and dried",
      "1 cup rice",
      "1 tsp ground cumin",
      "1 tbsp olive oil",
      "1/2 cup plain yogurt",
      "1/2 cucumber, diced",
      "Salt and black pepper",
    ],
    category: "Vegetarian",
    time: "35 min",
    accent: "bg-emerald-100 text-emerald-900",
    instructions: [
      "Cook the rice according to the package directions.",
      "Toss the chickpeas with olive oil, cumin, salt, and black pepper. Roast on a baking sheet at 425°F (220°C) for 20–25 minutes, shaking once, until crisp.",
      "Stir the diced cucumber into the yogurt and season with a pinch of salt.",
      "Divide the rice between bowls. Top with crispy chickpeas and cucumber yogurt.",
    ],
  },
  {
    slug: "ginger-sesame-salmon",
    name: "Ginger Sesame Salmon",
    description: "Tender salmon with ginger, sesame, and a savory soy glaze.",
    ingredients: [
      "4 salmon fillets",
      "1 tbsp grated fresh ginger",
      "2 tbsp soy sauce",
      "1 tbsp honey",
      "1 tsp sesame oil",
      "1 tsp sesame seeds",
      "2 cups cooked rice",
    ],
    category: "High protein",
    time: "28 min",
    accent: "bg-sky-100 text-sky-900",
    instructions: [
      "Heat the oven to 400°F (200°C) and place the salmon on a lined baking sheet.",
      "Mix the ginger, soy sauce, honey, and sesame oil. Spoon the mixture over the salmon.",
      "Bake for 12–15 minutes, until the salmon flakes easily with a fork.",
      "Serve over cooked rice and finish with sesame seeds.",
    ],
  },
  {
    slug: "apple-cinnamon-oatmeal",
    name: "Apple Cinnamon Oatmeal",
    description: "Warm oats topped with tender apples, cinnamon, and maple.",
    ingredients: [
      "1 cup rolled oats",
      "2 cups milk",
      "1 apple, diced",
      "1/2 tsp ground cinnamon",
      "1 tbsp maple syrup",
      "Pinch of salt",
    ],
    category: "Breakfast",
    time: "15 min",
    accent: "bg-violet-100 text-violet-900",
    instructions: [
      "Combine the oats, milk, diced apple, cinnamon, and salt in a saucepan.",
      "Bring to a gentle simmer over medium heat, stirring often.",
      "Cook for 5–7 minutes, until the oats are creamy and the apple is tender.",
      "Divide into bowls and drizzle with maple syrup.",
    ],
  },
];
